import '../styles/globals.css'
// import  '../styles/ttemplate/main.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Script from 'next/script'

function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Đào Duy Tùng - Web Developer</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
      <link rel="stylesheet" href="/assets/css/reset.css" type="text/css" />
      <link rel="stylesheet" href="/assets/css/bootstrap-grid.min.css" type="text/css" />
      <link rel="stylesheet" href="/assets/css/animations.css" type="text/css" />
      <link rel="stylesheet" href="/assets/css/perfect-scrollbar.css" type="text/css" />
      <link rel="stylesheet" href="/assets/css/owl.carousel.css" type="text/css" />
      <link rel="stylesheet" href="/assets/css/magnific-popup.css" type="text/css" />
      {/* <link rel="stylesheet" href="/assets/css/main.css" type="text/css" /> */}


      {/* <Script src="/assets/js/main.js" ></Script> */}

    </Head>

    <Component {...pageProps} />

    {/* <script src="/assets/js/main.js" ></script> */}
    <Script src="/assets/js/jquery-2.1.3.min.js" ></Script>
    <Script src="/assets/js/modernizr.custom.js" ></Script>
    <Script src="/assets/js/animating.js" ></Script>


    <Script src="/assets/js/imagesloaded.pkgd.min.js" ></Script>
    <Script src="/assets/js/perfect-scrollbar.min.js" ></Script>
    <Script src="/assets/js/jquery.shuffle.min.js" ></Script>
    <Script src="/assets/js/masonry.pkgd.min.js" ></Script>
    <Script src="/assets/js/owl.carousel.min.js" ></Script>
    <Script src="/assets/js/jquery.magnific-popup.min.js" ></Script>
    <Script src="/assets/js/validator.js" ></Script>
  </>
}

export default MyApp
